### PR TITLE
Wrapper to run wes filters

### PR DESCRIPTION
**Pull request by rhshah**
- Add a run_wes-filters.py
- Made filter_normal_panel.R to be compatible with new fillout
- Made filter_ffpe_pool.R to be compatible with new fillout
- Merged Nick’s additions
- Add Rscript —vanilla to applyFilters.sh to make it behave for singularity
- Add files in data folder, sample input maf and fill files and hotspot files to run with run_wes-filters.py
- Made a new folder tests with script to do unit test

### CODE REVIEW

**Comment by rhshah** [comment]
@lordzappo @kpjonsson @soccin  let me know if you think we can merge this, so @hisplan  can move forward

**Comment by lordzappo** [comment]
@rhshah @soccin @oliverhampton @kpjonsson --

I think we should fork this repo at this revision, and make Ronak the "main" maintainer of wes-filters, so he doesnt have to ask philip for merge reviews when philip is too busy.

we can take/continue development on mskcc/wes-filters, and philip can fork any revision to his personal repo, or to taylorlab if it needs to be private.  

RE repo name, philip correctly points out that if we intend to use these on all projects, we should rename the repo "ngs-filters".

I spoke to Oliver and Philip about this briefly and they think it's a good plan. 

If you want to rename the repo, I can do this easily today.  Otherwise, this is actually a no-op from computer science perspective...ronak is just empowered to merge his own PRs moving forward. 

*Finally, once the repo name is static, I will add "auto test on Pull Request" to jenkins for this repository.*

**Comment by rhshah** [comment]
Sure lets go ahead rename the repo and then merge, yes there is already a tests folder with unit test which will allow you to add auto test in Jenkins easily

**Comment by lordzappo** [comment]
@rhshah great. Name change made.  I am working on the jenkins build now.

**Comment by ckandoth** [comment]
@rhshah Just in case its needed, I made you an admin on this repo - at https://github.com/mskcc/ngs-filters/settings/collaboration

**Comment by rhshah** [comment]
Thanks @ckandoth

**Pull request merged**
